<?php
?></div>
</div>

<div id="page-footer" class="page-footer page-row">
    <div class="container-fluid home" style="margin-top:20px; page-break-before: always;">
        <div class="container">
            <div class="row">
                <div class="col-sm-4 text-xs-center text-sm-left">
                    <div class="visible-xs" style="margin:50px"></div>
                    <h4>Game Connect&nbsp;<small>Game whenever, wherever</small></h4>
                    <ul class="list-inline">

                        <li class="">
                            <a href="/play.php">Play Now</a>
                        </li>
                        <li class="">
                            <a href="/download.php">Mobile App</a>
                        </li>
                        <li class="">
                            <a href="/about.php">About</a>
                        </li>
                        <li class="">
                            <a href="/team.php">The Team</a>
                        </li>
                    </ul>
                    <p>Copyright &copy; <?php echo date("Y"); ?></p>
                    <div class="visible-xs" style="margin:50px"></div>
                </div>
<!--                <div class="col-sm-4 text-xs-center text-sm-left">
                    
                    <div class="visible-xs" style="margin:50px"></div>
                </div>
                <div class="col-sm-4 text-xs-center text-sm-left">
                    
                    <div class="visible-xs" style="margin:50px"></div>
                </div>-->
            </div>
        </div>
    </div>
</div>
</body>
