<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<style><?php //include "../assets/css/style.css.php"; ?></style>
<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
<link rel="icon" type="image/x-icon" href="/favicon.ico" />
<link rel="icon" type="image/png" href="/assets/img/navicon.png">
<script src="/assets/js/sweetalert.min.js"></script>
<link rel="stylesheet" type="text/css" href="/assets/css/sweetalert.css">
<link rel="stylesheet" type="text/css" href="/assets/css/font-awesome.css">
<link rel="stylesheet" type="text/css" href="/assets/css/simplex-bootstrap.min.css.php">
<link rel="stylesheet" type="text/css" href="/assets/css/style.css.php">
<link rel="stylesheet" type="text/css" href="/assets/css/round-about.css">
<script src="/assets/js/portal.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1.0">